#pragma once
// #define MASTER_LEFT
#define MASTER_RIGHT
// #define EE_HANDS

// pimoroni zone
#define PIMORONI_TRACKBALL_ENABLE
#define PIMORONI_TRACKBALL_ROTATE
#define POINTING_DEVICE_TASK_THROTTLE_MS 8

#define COMBO_TERM_PER_COMBO
#define COMBO_PROCESS_KEY_RELEASE
#define COMBO_HOLD_TERM 140

#define TAPPING_TOGGLE 2

#define TAPPING_FORCE_HOLD_PER_KEY
#define TAPPING_TERM 180
#define TAPPING_TERM_PER_KEY
#define IGNORE_MOD_TAP_INTERRUPT

#undef MOUSEKEY_DELAY
#define MOUSEKEY_DELAY          0
#undef MOUSEKEY_INTERVAL
#define MOUSEKEY_INTERVAL       16
#undef MOUSEKEY_WHEEL_DELAY
#define MOUSEKEY_WHEEL_DELAY    0
#undef MOUSEKEY_MAX_SPEED
#define MOUSEKEY_MAX_SPEED      6
#undef MOUSEKEY_TIME_TO_MAX
#define MOUSEKEY_TIME_TO_MAX    64
    